{
 "title": "Organization Overview",
 "description": "A Top-Level analysis of the Organization",
 "tags": [ "production" ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Heros",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total URLs Monitored",
     "type": "stat",
     "description": "Number of URLs crawled",
     "gridPos": { "h": 3, "w": 8, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT count(*)\nFROM targets.urls;"
      }
     ]
    },
    {
     "title": "Domains",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "Select count(*)\nfrom targets.domains;"
      }
     ]
    },
    {
     "title": "Sitemaps",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 4, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "Select count(*)\nfrom targets.sitemaps;"
      }
     ]
    }
   ]
  },
  { "title": "Government Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Government URLs",
   "type": "stat",
   "description": "All monitored US Government URLs",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(*)\nFROM targets.urls\nwhere url ilike '%.gov%'\nOR url ilike '%.mil%';"
    }
   ]
  },
  {
   "title": "Government Domains",
   "type": "stat",
   "description": "Count of US Govt Domains",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "Select count(*)\nfrom targets.domains\nwhere domain ilike '%.gov%'\nOR domain ilike '.mil';"
    }
   ]
  },
  {
   "title": "Government Sitemaps",
   "type": "stat",
   "description": "Count of US Government Sitemaps",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "Select count(*)\nfrom targets.sitemaps\nwhere url ilike '%.gov%'\nor url ilike '%.mil%';"
    }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Axe Summary | WCAG Violations Only",
   "type": "table",
   "gridPos": { "h": 9, "w": 13, "x": 0, "y": 9 },
   "targets": [
    {
     "rawSql": "SELECT \n  td.\"domain\" AS \"Domain\",        \n  tu.url AS \"URL\",             \n  ar.scan_id AS \"Scan id\",         \n  -- ar.rule_type,       \n  ar.axe_id AS \"axe id\",          \n  ar.impact AS \"Impact\", \n\n  CONCAT(\n    ROUND(EXTRACT(EPOCH FROM (now() - asd.created_at)) / 60), \n    ' minutes ago'\n  ) AS \"Time since created\"  \n\n  -- asd.created_at       \nFROM \n  axe.rules AS ar\nJOIN\n  axe.scan_data AS asd ON asd.id = ar.scan_id\nJOIN\n  targets.urls AS tu ON tu.id = asd.url_id\nJOIN \n  targets.domains AS td ON td.id = tu.domain_id\nWHERE \n  ar.rule_type = 'violations' AND \n  ar.id IN (\n    SELECT DISTINCT r.id\n    FROM \n      axe.rules AS r,\n      jsonb_array_elements_text(r.tags) AS tag\n    WHERE \n      r.rule_type = 'violations' AND \n      tag LIKE '%wcag%'\n  )\n  AND asd.created_at >= $__timeFrom() AND asd.created_at <= $__timeTo()\n  ORDER BY asd.created_at DESC;"
    }
   ]
  }
 ]
}