{
 "title": "System Overview",
 "description": "The technical infrastructure of GovA11y",
 "tags": [ "production" ],
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "db_schema",
    "label": "Database Schemas",
    "query": "axe, events, orgs, refs, results, targets"
   }
  ]
 },
 "panels": [
  { "title": "Database Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Active Connections",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 11, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  COUNT(*) AS \"Active Connections\"\nFROM\n  pg_stat_activity\nWHERE\n  state = 'active';\n"
    }
   ]
  },
  {
   "title": "Rows Inserted, Updated, and Deleted",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 11, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  relname AS \"Table\",\n  n_tup_ins AS \"Rows Inserted\",\n  n_tup_upd AS \"Rows Updated\",\n  n_tup_del AS \"Rows Deleted\"\nFROM\n  pg_stat_all_tables\nWHERE\n  schemaname NOT IN ('pg_catalog', 'information_schema')\n  AND relname not ilike 'pg_toast%'\nORDER BY\n  relname;\n"
    }
   ]
  },
  {
   "title": "Connection Utilization",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  COUNT(*) * 100 / current_setting('max_connections')::integer AS \"Connection Utilization\"\nFROM\n  pg_stat_activity;\n"
    }
   ]
  },
  {
   "title": "Cache Hit Ratio",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 5, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  (sum(heap_blks_hit) / (sum(heap_blks_hit) + sum(heap_blks_read))) * 100 AS \"Cache Hit Ratio\"\nFROM\n  pg_statio_user_tables;\n"
    }
   ]
  },
  { "title": "Activity", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Sequential and Index Scans",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "rawSql": "SELECT\n  relname AS \"Table\",\n  seq_scan AS \"Sequential Scans\",\n  idx_scan AS \"Index Scans\"\nFROM\n  pg_stat_all_tables\nWHERE\n  schemaname NOT IN ('pg_catalog', 'information_schema')\n  AND relname not ilike 'pg_toast%'\nORDER BY\n  relname;\n"
    }
   ]
  },
  { "title": "Schemas", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 }, "repeat": "db_schemas" },
  {
   "title": "How many tables are in each schema?",
   "type": "barchart",
   "description": "The number of tables in each schema",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "rawSql": "SELECT table_schema AS \"Schema\", COUNT(*) AS \"Tables\"\nFROM information_schema.tables\nWHERE table_catalog = 'a11ydata'\nAND table_schema IN ('targets', 'results', 'refs', 'axe', 'events', 'orgs')\nGROUP BY table_schema;"
    }
   ]
  },
  {
   "title": "Schema Size: ${db_schema}",
   "type": "table",
   "description": "Table, column, & row breakdown for each table in ${db_schema}.",
   "gridPos": { "h": 9, "w": 8, "x": 9, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "rawSql": "WITH table_info AS (\n  SELECT\n    table_name AS \"Table\",\n    COUNT(*) AS \"Column Count\"\n  FROM\n    information_schema.columns\n  WHERE\n    table_catalog = 'a11ydata'\n    AND table_schema = '${db_schema}'\n  GROUP BY\n    table_name\n),\nrow_counts AS (\n  SELECT\n    table_name,\n    (xpath('/row/cnt/text()', xml_count))[1]::text::bigint as \"Row Count\"\n  FROM (\n    SELECT\n      table_name,\n      table_schema,\n      query_to_xml('SELECT count(*) as cnt FROM ' || quote_ident(table_schema) || '.' || quote_ident(table_name), false, true, '') as xml_count\n    FROM\n      information_schema.tables\n    WHERE\n      table_catalog = 'a11ydata'\n      AND table_schema = '${db_schema}'\n  ) as sub_query\n)\nSELECT\n  ti.\"Table\",\n  ti.\"Column Count\",\n  rc.\"Row Count\"\nFROM\n  table_info ti\nJOIN row_counts rc ON ti.\"Table\" = rc.table_name\nORDER BY\n  ti.\"Table\";\n"
    }
   ]
  },
  { "title": "Database Structure", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "Dead Rows and Unused Indexes",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "rawSql": "SELECT\n  relname AS \"Table\",\n  n_dead_tup AS \"Dead Rows\",\n  n_mod_since_analyze AS \"Unused Indexes\"\nFROM\n  pg_stat_all_tables\nWHERE\n  schemaname NOT IN ('pg_catalog', 'information_schema')\n  AND relname not ilike 'pg_toast%'\nORDER BY\n  relname;\n"
    }
   ]
  },
  {
   "title": "Disk Usage by Tables",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 8, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT\n  relname AS \"Table\",\n  pg_total_relation_size(C.oid) / 1024 AS \"Size (kB)\"\nFROM\n  pg_class C\nLEFT JOIN pg_namespace N ON (N.oid = C.relnamespace)\nWHERE\n  nspname NOT IN ('pg_catalog', 'information_schema') AND\n  nspname !~ '^pg_toast' AND\n  relkind = 'r'\nORDER BY\n  pg_total_relation_size(C.oid) DESC;\n"
    }
   ]
  },
  { "title": "Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  {
   "title": "Checkpoint Performance",
   "type": "text",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 40 },
   "options": {
    "content": "\n\n### Checkpoint Write Time\nThe total time spent writing checkpoint-related data to disk, measured in milliseconds. This metric helps you understand the overall efficiency and performance of the checkpoint process. Higher values may indicate potential bottlenecks in the system's I/O performance during checkpoint operations.\n\n### Checkpoint Sync Time\nThe total time spent synchronizing the file system after a checkpoint has been written, measured in milliseconds. This metric helps you understand the overall performance of the file system and how it may impact the checkpoint process. Higher values may indicate potential issues with file system performance or other underlying storage system factors.\n\n### Scheduled Checkpoints\nThe total number of checkpoints that were initiated automatically by the PostgreSQL database due to various system parameters, such as checkpoint_timeout or max_wal_size. Monitoring this value can help you understand the database's checkpoint behavior and adjust the system parameters if necessary to balance performance and data consistency.\n\n### Requested Checkpoints\nThe total number of checkpoints that were requested explicitly by users, either by executing the CHECKPOINT command or by other means (e.g., during a database backup). Monitoring this value can help you track user-initiated checkpoint operations and identify any patterns that may affect the database's performance."
   }
  },
  {
   "title": "Checkpoint Performance",
   "type": "stat",
   "gridPos": { "h": 5, "w": 16, "x": 8, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  checkpoints_timed AS \"Scheduled Checkpoints\",\n  checkpoints_req AS \"Requested Checkpoints\"\nFROM\n  pg_stat_bgwriter;"
    },
    {
     "rawSql": "SELECT\n  checkpoint_write_time AS \"Checkpoint Write Time\",  -- in ms\n  checkpoint_sync_time AS \"Checkpoint Sync Time\" --ms\nFROM\n  pg_stat_bgwriter;"
    }
   ]
  }
 ]
}