apiVersion: 1

datasources:
  - name: Postgres | a11ydata
    type: postgres
    url: postgres:5432
    database: a11ydata
    user: grafanareader
    secureJsonData:
      password: "super_grafana_password"
    jsonData:
      sslmode: "disable" # disable/require/verify-ca/verify-full
      maxOpenConns: 10
      maxIdleConns: 5
      connMaxLifetime: 14400
      postgresVersion: 1500 # 903=9.3, 904=9.4, 905=9.5, 906=9.6, 1000=10
      timescaledb: false